export default {
    REQUESTED_POSTS: 'REQUESTED_POSTS',
    REQUESTED_ADD_POST: 'REQUESTED_ADD_POST',
    REQUESTED_EDIT_POST: 'REQUESTED_EDIT_POST',
    REQUESTED_DELETE_POSTS: 'REQUESTED_DELETE_POSTS',
    REQUESTED_SUCCEEDED: 'REQUESTED_SUCCEEDED',
    REQUESTED_FAILED: 'REQUESTED_FAILED',
    FETCHED_POSTS: 'FETCHED_POSTS',

    GET_POSTS: 'GET_POSTS',
    ADD_POST: 'ADD_POST',
    EDIT_POST: 'EDIT_POST',
    DELETE_POSTS: 'DELETE_POSTS',
}